import express from 'express';
import  upload  from '../middlewares/multer.js';
import { allBlogs, createBlog, deleteBlog, singleBlog, userBlogs } from '../controllers/blog.controller.js';
import { isAuthenticated } from '../middlewares/isAuthenticated.js';
const router=express.Router();
router.post("/create",isAuthenticated, upload.single("image"),createBlog);
router.get("/all",allBlogs);
router.delete("/delete/:id",isAuthenticated,deleteBlog);
router.get('/user/blogs',isAuthenticated,userBlogs);
router.get('/user/blog/:id',isAuthenticated,singleBlog);
export default router;